default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: animetalk_development
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: animetalk_test
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: animetalk_production
  url: <%= ENV['DATABASE_URL'] %>
