# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: postgres
#   password: <%= ENV['DATABASE_PASSWORD'] %>

# development:
#   <<: *default
#   database: animetalk_development

# test:
#   <<: *default
#   database: animetalk_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>